### Signup - create user
POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "Secret123!"
}

### Login - obtain token
# @name login
POST http://127.0.0.1:8000/login/
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "Secret123!"
}

### Refresh Token - obtain new token using refresh token
POST http://127.0.0.1:8000/refresh-token/
Content-Type: application/json

{
    "refreshToken": "PASTE_YOUR_REFRESH_TOKEN_HERE"
}

### Login with provider (Google) - obtain new token using oAuth ID token
POST http://127.0.0.1:8000/login/
Content-Type: application/json

{
    "token": "PASTE_YOUR_ID_TOKEN_HERE"
}

### Get all parking lots
GET http://127.0.0.1:8000/parking-lots/
Content-Type: application/json

### Get all parking lots of managed by city operator
GET http://127.0.0.1:8000/cadmin/parking-lots/
Authorization: Bearer {{login.response.body.idToken}}
Content-Type: application/json

### Add a new parking lot
POST http://127.0.0.1:8000/cadmin/parking-lots/
Authorization: Bearer {{login.response.body.idToken}}
Content-Type: application/json

{
    "name": "Central Park Lot",
    "latitude": 40.785091,
    "longitude": -73.968285,
    "address": "123 Main St, Anytown, USA"
}

### Update an existing parking lot
PUT http://127.0.0.1:8000/cadmin/parking-lots/
Authorization: Bearer {{login.response.body.idToken}}
Content-Type: application/json

{
    "id": 1,
    "name": "Updated Central Park Lot",
    "address": "456 Elm St, Anytown, USA"
}

### Delete an existing parking lot
DELETE http://127.0.0.1:8000/cadmin/parking-lots/
Authorization: Bearer {{login.response.body.idToken}}
Content-Type: application/json

{
    "id": 1
}

### Get all parking spots in a parking lot managed by city operator
GET http://127.0.0.1:8000/cadmin/parking-spots/
Authorization: Bearer {{login.response.body.idToken}}
Content-Type: application/json

{
    "parking_lot_id": 1
}

### Add a new parking spot to a parking lot managed by city operator
# @name add_parking_spot
POST http://127.0.0.1:8000/cadmin/parking-spots/
Authorization: Bearer {{login.response.body.idToken}}
Content-Type: application/json

{
    "parking_lot_id": 1
}

### Delete a parking spot from a parking lot managed by city operator
DELETE http://127.0.0.1:8000/cadmin/parking-spots/
Authorization: Bearer {{login.response.body.idToken}}
Content-Type: application/json

{
    "id": 1
}

### Add parking events to a parking spot
POST http://127.0.0.1:8000/parking-events/
Authorization: Bearer {{add_parking_spot.response.body.parking_spot.auth_code}}
Content-Type: application/json

{
    "occupied": true
}