# Generated by Django 5.2.7 on 2025-12-02 09:28

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityOperator',
            fields=[
                ('id', models.CharField(max_length=28, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invalid Firebase UID format.', regex='^[A-Za-z0-9_\\-]{28}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(max_length=28, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invalid Firebase UID format.', regex='^[A-Za-z0-9_\\-]{28}$')])),
            ],
        ),
        migrations.CreateModel(
            name='OperatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='Firebase UID of the user requesting operator access', max_length=28, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Firebase UID format.', regex='^[A-Za-z0-9_\\-]{28}$')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about the request', null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('capacity', models.IntegerField(default=0)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, help_text='Price in DKK per hour', max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invalid Firestore document ID.', regex='^[A-Za-z0-9_\\-]+$')])),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkinglot')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code_hash', models.CharField(max_length=64, unique=True)),
                ('auth_code_prefix', models.CharField(max_length=12)),
                ('event_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.eventlist')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkinglot')),
            ],
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cityoperator')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkinglot')),
            ],
            options={
                'unique_together': {('operator', 'parking_lot')},
            },
        ),
    ]
