# Generated by Django 5.2.7 on 2025-11-21 09:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityOperator',
            fields=[
                ('id', models.CharField(max_length=28, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invalid Firebase UID format.', regex='^[A-Za-z0-9_\\-]{28}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(max_length=28, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invalid Firebase UID format.', regex='^[A-Za-z0-9_\\-]{28}$')])),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cityoperator')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkinglot')),
            ],
        ),
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invalid Firestore document ID.', regex='^[A-Za-z0-9_\\-]+$')])),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkinglot')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('event_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.eventlist')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkinglot')),
            ],
        ),
    ]
