# Generated by Django 5.2.7 on 2025-11-19 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkinglot",
            name="auth_code",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="parkingspot",
            name="auth_code",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=50, unique=True
            ),
        ),
    ]
