# Generated by Django 5.2.7 on 2025-11-19 14:39

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='longitude',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(12.5683, 55.6761), geography=True, srid=4326),
        ),
    ]
